version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=afs][pdgka[ojgah
      - POSTGRES_USER=second
    ports:
      - "5432:5432"
  redis:
    image: redis:5
    command: redis-server --requirepass afs][pdgka[ojgah
    ports:
      - "6379:6379"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
