version: '2'

services:
  db:
    image: postgres
    network_mode: "host"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    network_mode: "host"
