# Generated by Django 2.0.13 on 2019-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190722_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('LOB', 'Lobby'), ('PLA', 'Playing'), ('END', 'Ended')], default='LOB', max_length=3),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='currently_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='currently_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
