# Generated by Django 2.0.13 on 2019-08-08 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190731_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='current_card',
            field=models.CharField(default='{}', max_length=2048),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='start_of_turn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='state',
            field=models.CharField(choices=[('PRE', 'Before reading the card'), ('REA', 'Reading the card'), ('AFT', 'After reading the card')], default='AFT', max_length=3),
        ),
    ]
