# Generated by Django 2.0.13 on 2019-08-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190808_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-score']},
        ),
    ]
