# Generated by Django 2.0.13 on 2019-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190812_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.CharField(choices=[('NL', 'Dutch'), ('UK', 'English')], default='NL', max_length=2),
        ),
    ]
