# Generated by Django 3.2.18 on 2023-05-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_team_pion_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pion_filename',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
