# Generated by Django 3.2.18 on 2023-05-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_team_pion_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('EAS', 'Easy'), ('MED', 'Medium'), ('HAR', 'Hard')], default='MED', max_length=3),
        ),
    ]
