# Generated by Django 2.0.13 on 2019-08-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='text',
        ),
        migrations.AddField(
            model_name='word',
            name='added_by',
            field=models.CharField(default='Thijs', max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('NL', 'Dutch'), ('UK', 'English')], default='NL', max_length=2),
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default='niks', max_length=25),
            preserve_default=False,
        ),
    ]
