# Generated by Django 2.0.13 on 2019-08-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20190808_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=32),
        ),
    ]
