# Generated by Django 2.0.13 on 2019-08-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_auto_20190808_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
            ],
        ),
    ]
