# Generated by Django 2.0.13 on 2019-08-10 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_optionalword'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
