# Generated by Django 2.0.13 on 2019-08-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_word_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalword',
            name='word',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
