# Generated by Django 2.0.13 on 2019-08-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_auto_20190812_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalenglishword',
            options={'ordering': ['-id']},
        ),
    ]
