# Generated by Django 2.0.13 on 2019-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='words_explained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='words_explained_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='words_guessed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='words_guessed_correct',
            field=models.IntegerField(default=0),
        ),
    ]
